### ISSUE TITLE
Two files with similar names

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Hacktoberfest-PR-for-beginners#8]
In `Hacktoberfest-PR-for-beginners/C codes/`, there are two files with the name factorial. One with factorial.c and other with Factorial.c

Link: https://github.com/ALPHAVIO/Hacktoberfest-PR-for-beginners/tree/master/C%20codes

When I tried to clone the repo, I got the following warning and one of the file didn't get cloned rather was replaced by the other one. 

<img width="687" alt="Screenshot 2021-10-02 at 12 47 29 AM" src="https://user-images.githubusercontent.com/73700530/135675053-df3b44ca-2a35-4f03-aae8-8a8fb775d8d2.png">

So, similar problems might be faced by other contributors.
It would be more better, if some contributor(or beginners in open source) fix it. 🙌

**I won't be working on it, just raising this issue and leaving it for others to fix.**    👍

**Comment by AkhileshManda** [comment]
worked on it and created a pr
